apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: app-container
    image: myapp:latest
    command: ["./app"]
    args: ["arg1", "arg2"]
  - name: db-container
    image: postgres:latest
    env:
    - name: POSTGRES_USER
      value: myuser
    - name: POSTGRES_PASSWORD
      value: mypassword
  - name: cache-container
    image: redis:latest
    ports:
    - containerPort: 6379
      protocol: TCP
    volumeMounts:
    - name: cache-volume
      mountPath: /data/cache
  volumes:
  - name: cache-volume
    emptyDir: {}
